export const ENV_VARIABLES = {
  DATABASE: {
    CLIENT: 'DATABASE_CLIENT',
    HOST: 'DATABASE_HOST',
    USER: 'DATABASE_USER',
    PASSWORD: 'DATABASE_PASSWORD',
    NAME: 'DATABASE_NAME',
    PORT: 'DATABASE_PORT',
  },
  APP_PORT: 'PORT',
};

export enum NODE_ENV {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}
